// Mapping of words/phrases to emojis
const emojiDictionary = {
    "happy": "😊",
    "sad": "😞",
    "love": "❤️",
    "angry": "😠",
    "excited": "🤩",
    "cool": "😎",
    "yes": "👍",
    "no": "👎",
    "party": "🎉",
    "friend": "👯",
    "cat": "🐱",
    "dog": "🐶",
    "coffee": "☕",
    "pizza": "🍕",
    "sun": "🌞",
    "moon": "🌙",
    "star": "⭐",
    "ice cream sandwich": "🍦🍔",
    "lost my train of thought": "🚂💭🚫🧐",
    "you're a joke": "🫵🤣",
    "lOOK at this!": "✨👀",
    "piece of cake": "🍰👌",
    "better late than never": "🕰️⏳",
    "couch potato": "🛋️🥔",
    "don't judge a book by its cover": "📖🙈",
    "break a leg": "🍖🦵",
    "cat got your tongue?": "🐱👅❓",
    "under the weather": "🌧️🤒",
    "bite the bullet": "💉💥",
    "curiosity killed the cat": "🧐🐱💀",
    "burning the midnight oil": "🕯️🔥",
    "nose to the grindstone": "👃🪓🪵",
    "hit the nail on the head": "🔨🧠",
    "in a pickle": "🥒😖",
    "don't cry over spilled milk": "🐄🥛💧😢",
    "a bird in the hand is worth two in the bush": "🦜🤲🤷‍♂️🌳",
    "on cloud nine": "☁️9",
    "like a fish out of water": "🐟🚫🌊",
    "spill the beans": "🫘💦",
    "the ball is in your court": "⚽👉🏠",
    "a penny for your thoughts": "💰💭",
    "a rolling stone gathers no moss": "🪨💨🍃",
    "barking up the wrong tree": "🐕🌳",
    "taco Tuesday": "🌮🍹",
    "sushi night": "🍣🍱🍷",
    "donut worry": "🍩😌",
    "smoothie time": "🥤🍓🍌",
    "you’re my everything": "🍕🍔🍟",
    "all you can eat": "🍽️🍽️🍽️",
    "coffee break": "☕💼",
    "wine o’clock": "🍷🕔",
    "grill time": "🍖🔥🍽️",
    "time for dessert": "🍰⏰",
    "i’m stuffed": "🍽️🍗🍰💥",
    "choco-holic": "🍫🍩🍪",
    "fruit salad": "🍓🍇🍍🍉",
    "spicy food": "🌶️🔥",
    "pizza party": "🍕🎉",
    "monkey business": "🐒🤪",
    "cat nap": "🐱💤",
    "dog days of summer": "🐶☀️",
    "herd mentality": "🐄🐑🐐",
    "fish out of water": "🐟🚫🌊",
    "fighting like cats and dogs": "🐱🐶💥",
    "cuddling time": "🐻🫂",
    "feeling lionhearted": "🦁💪",
    "bear hugs": "🐻🤗",
    "taco night": "🌮🌙",
    "battery running low": "🔋🔴",
    "upgrade complete": "🔧⚙️✅",
    "wiFi problems": "📶🚫",
    "i’ve had enough of this": "🖥️🖱️💥",
    "virtual reality": "🕶️💻🌐",
    "sending a text": "📱✉️",
    "it’s charging": "🔌⚡",
    "programmed for success": "👾💻📈",
    "lost connection": "🌐❌🔌",
    "heartbreaker": "💔💔",
    "love at first sight": "😍👀❤️",
    "soulmate": "💕✨",
    "not feeling it": "😕🚫❤️",
    "friendzone": "👫❌❤️",
    "feeling lovey-dovey": "💘💑",
    "heart and soul": "❤️💫",
    "couple goals": "👩‍❤️‍👨🌟",
    "married life": "💍👰‍♀️🤵‍♂️",
    "making up": "😘🤗",
    "hustling": "🧑‍💼💼💪",
    "work hard, play hard": "💼🍻",
    "deadline approaching": "⏰⚡",
    "teamwork makes the dream work": "👥💭✨",
    "coffee is my boss": "☕👔",
    "can’t stop, won’t stop": "🔄💯",
    "boss mode": "👑💼",
    "all-nighter": "🌙💻☕",
    "making progress": "🔜🚀",
    "productivity boost": "📈⚡",
    "birthday party": "🎂🎉🎈",
    "celebrate good times": "🎊🎶🎉",
    "holiday vibes": "🎄❄️🎁",
    "throwing a party": "🎉🍾🎶",
    "fireworks show": "🎆🎇",
    "wedding vibes": "💍👰‍♀️🤵‍♂️",
    "happy New Year": "🎆🎉🥂",
    "graduation day": "🎓📚",
    "festival time": "🎪🎉",
    "christmas time": "🎄🎅✨",
    "bad hair day": "🦰💨",
    "messing around": "🧑‍🎤🤪",
    "starstruck": "🌟🤩",
    "going viral": "🌐🔥💥",
    "feeling magical": "🪄✨",
    "lost in thought": "🤔🌌",
    "resting mode": "😴💤",
    "too cool for school": "😎🏫",
    "catch me if you can": "🏃‍♂️💨",
    "over the top": "🔝🤩",
    "feeling blue": "💙😞",
    "that’s lit!": "🔥👌",
    "i’m falling for you": "🍂❤️",
    "not amused": "😒🙄",
    "feeling groovy": "🕺💃✨",
    "on top of the world": "🌍⬆️",
    "sick of this": "🤢🚫",
    "i’m dead": "💀🤣",
    "shook": "😳😱",
    "feeling lazy": "🛋️😴",
    "don’t mess with me": "🚫⚔️",
    "guilty pleasure": "🍫😅",
    "i’m over it": "🙄🙅‍♂️",
    "nervous": "😬🤔",
    "in love": "💖😊",
    "you’re killing me!": "💀😭",
    "just hanging out": "🙆‍♂️🌿",
    "crushing it": "💪🏆",
    "feeling myself": "💁‍♀️💃",
    "happy": "😊",
    "sad": "😞",
    "angry": "😠",
    "excited": "🤩",
    "surprised": "😮",
    "love": "❤️",
    "hug": "🤗",
    "cry": "😢",
    "laugh": "😂",
    "confused": "😕",
    "embarrassed": "😳",
    "bored": "😒",
    "tired": "😴",
    "shy": "🙈",
    "fear": "😱",
    "sad but Strong": "💪😔",
    "grateful": "🙏",
    "jealous": "😒💚",
    "stressed": "😩",
    "relieved": "😌",
    "motivated": "🚀💪",
    "mischievous": "😈",
    "thumbs up": "👍",
    "thumbs down": "👎",
    "high five": "🙌",
    "fist bump": "👊",
    "facepalm": "🤦‍♂️",
    "victory": "✌️",
    "clapping": "👏",
    "waving": "👋",
    "nope": "🚫",
    "okay": "👌",
    "applause": "👏👏👏",
    "finger pointing": "👉",
    "shushing": "🤫",
    "praying": "🙏",
    "dog": "🐶",
    "cat": "🐱",
    "rabbit": "🐰",
    "elephant": "🐘",
    "lion": "🦁",
    "tiger": "🐅",
    "bear": "🐻",
    "monkey": "🐒",
    "fish": "🐟",
    "horse": "🐴",
    "bird": "🐦",
    "chicken": "🐔",
    "cow": "🐄",
    "penguin": "🐧",
    "frog": "🐸",
    "snake": "🐍",
    "fox": "🦊",
    "panda": "🐼",
    "koala": "🐨",
    "giraffe": "🦒",
    "butterfly": "🦋",
    "dragon": "🐉",
    "octopus": "🐙",
    "turtle": "🐢",
    "whale": "🐋",
    "shark": "🦈",
    "horse with wings": "🐴🦄",
    "pizza": "🍕",
    "burger": "🍔",
    "fries": "🍟",
    "hot dog": "🌭",
    "sushi": "🍣",
    "ice Cream": "🍦",
    "donut": "🍩",
    "cake": "🍰",
    "cupcake": "🧁",
    "coffee": "☕",
    "tea": "🍵",
    "watermelon": "🍉",
    "apple": "🍎",
    "banana": "🍌",
    "grapes": "🍇",
    "orange": "🍊",
    "pineapple": "🍍",
    "strawberry": "🍓",
    "lemon": "🍋",
    "avocado": "🥑",
    "tomato": "🍅",
    "carrot": "🥕",
    "corn": "🌽",
    "potato": "🥔",
    "broccoli": "🥦",
    "chili": "🌶",
    "rice": "🍚",
    "peanut": "🥜",
    "cheese": "🧀",
    "bread": "🍞",
    "chocolate": "🍫",
    "popcorn": "🍿",
    "cocktail": "🍸",
    "beer": "🍺",
    "wine": "🍷",
    "whiskey": "🥃",
    "running": "🏃‍♂️",
    "swimming": "🏊‍♂️",
    "cycling": "🚴‍♂️",
    "football": "🏈",
    "basketball": "🏀",
    "tennis": "🎾",
    "soccer": "⚽",
    "baseball": "⚾",
    "golf": "⛳",
    "bowling": "🎳",
    "gymnastics": "🤸‍♀️",
    "boxing": "🥊",
    "yoga": "🧘‍♀️",
    "skiing": "🎿",
    "skateboarding": "🛹",
    "hiking": "🥾",
    "dancing": "💃",
    "skating": "⛸️",
    "camping": "🏕️",
    "fishing": "🎣",
    "climbing": "🧗‍♂️",
    "playing cards": "🃏",
    "bow and arrow": "🏹",
    "playing guitar": "🎸",
    "playing piano": "🎹",
    "car": "🚗",
    "bicycle": "🚲",
    "bus": "🚌",
    "train": "🚆",
    "airplane": "✈️",
    "helicopter": "🚁",
    "boat": "🚤",
    "rocket": "🚀",
    "motorcycle": "🏍️",
    "scooter": "🛴",
    "taxi": "🚖",
    "tram": "🚊",
    "ambulance": "🚑",
    "fire Truck": "🚒",
    "sun": "🌞",
    "cloud": "☁️",
    "rain": "🌧️",
    "lightning": "⚡",
    "snowflake": "❄️",
    "wind": "🌬️",
    "rainbow": "🌈",
    "volcano": "🌋",
    "mountain": "🏔️",
    "tree": "🌳",
    "flower": "🌸",
    "leaf": "🍃",
    "cactus": "🌵",
    "star": "⭐",
    "moon": "🌙",
    "sunset": "🌅",
    "ocean": "🌊",
    "desert": "🏜️",
    "forest": "🌲",
    "waterfall": "🌊💦",
    "laptop": "💻",
    "phone": "📱",
    "camera": "📷",
    "headphones": "🎧",
    "speaker": "🔊",
    "tv": "📺",
    "watch": "⌚",
    "joystick": "🎮",
    "keyboard": "⌨️",
    "mouse": "🖱️",
    "usb": "🖲️",
    "satellite": "🛰️",
    "robot": "🤖",
    "smartwatch": "⌚📱",
    "heart": "❤️",
    "fire": "🔥",
    "star": "⭐",
    "checkmark": "✔️",
    "cross mark": "❌",
    "lightning Bolt": "⚡",
    "diamond": "💎",
    "crown": "👑",
    "money bag": "💰",
    "gem": "💎",
    "gift": "🎁",
    "trophy": "🏆",
    "ribbon": "🎀",
    "skull": "💀",
    "alien": "👽",
    "crystal Ball": "🔮",
    "lock": "🔒",
    "key": "🗝️",
    "hourglass": "⏳",
    "alarm clock": "⏰",
    "wrench": "🔧",
    "birthday cake": "🎂",
    "party popper": "🎉",
    "confetti ball": "🎊",
    "christmas tree": "🎄",
    "gift": "🎁",
    "fireworks": "🎆",
    "halloween": "🎃",
    "easter egg": "🐣",
    "valentine’s day": "💝",
    "new year": "🎆🎉",
    "hanukkah": "🕎",
    "diwali": "🪔"

};

// Function to translate text to emojis
function translateToEmoji() {
    // Ensure inputText is a string
    inputText = document.getElementById("inputText").value

    if (typeof inputText !== 'string') {
        throw new Error('Input must be a string');
    }

    let translatedText = inputText.toLowerCase();  // Now safe to call toLowerCase

    // Iterate through the dictionary and replace words/phrases
    Object.keys(emojiDictionary).forEach((word) => {
        const regex = new RegExp(`\\b${word}\\b`, 'gi');  // Case insensitive matching
        translatedText = translatedText.replace(regex, emojiDictionary[word]);
    });

    document.getElementById("outputText").textContent = translatedText;
}

document.getElementById("translateBtn").addEventListener("click", translateToEmoji);

